version: '3'
services:
  db:
    image: mariadb:latest
    restart: always
    env_file:
      - /.env
    volumes:
      - ./data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"  